squadron_command_staff:
  - symbol: CC
    title: 'Commander'
  - symbol: CD
    title: 'Deputy Commander'
  - symbol: CCN
    title: 'NCO Advisor'
  - symbol: SE
    title: 'Safety Officer'
  - symbol: HC
    title: 'Chaplain'
senior_program_staff:
  - symbol: AE
    title: 'Aerospace Education Officer'
  - symbol: AEC
    title: 'Cyber Education Officer'
  - symbol: DO
    title: 'Operations Officer'
  - symbol: ES
    title: 'Emergency Services Officer'
  - symbol: ESA
    title: 'Alerting Officer'
  - symbol: EST
    title: 'Emergency Services Training Officer'
  - symbol: HCI
    title: 'Character Development Instructor'
  - symbol: LD
    title: 'Leadership Officer'
  - symbol: LDA
    title: 'Activities Officer'
  - symbol: PD
    title: 'Education and Training Officer'
  - symbol: PT
    title: 'Fitness Officer'
  - symbol: RR
    title: 'Recruiting & Retention Officer'
senior_support_staff:
  - symbol: DA
    title: 'Administrative Officer'
  - symbol: DC
    title: 'Communications Officer'
  - symbol: DP
    title: 'Personnel Officer'
  - symbol: FM
    title: 'Finance Officer'
  - symbol: IT
    title: 'Information Technology Officer'
  - symbol: LG
    title: 'Logistics Officer'
  - symbol: PA
    title: 'Public Affairs Officer'
cadet_command_staff:
  - symbol: C/CC
    title: 'Cadet Commander'
    min_grade: 'C/2d Lt'
    max_grade: 'C/Col'
  - symbol: C/CDO
    title: 'Cadet Deputy Commander for Operations'
    min_grade: 'C/2d Lt'
    max_grade: 'C/Col'
  - symbol: C/CDS
    title: 'Cadet Deputy Commander for Support'
    min_grade: 'C/2d Lt'
    max_grade: 'C/Col'
  - symbol: C/CCF
    title: 'First Sergeant'
    min_grade: 'C/MSgt'
    max_grade: 'C/CMSgt'
cadet_support_staff:
  - symbol: C/AE
    title: 'Cadet Aerospace Education Officer'
    max_grade: 'C/Col'
    min_grade: 'C/2d Lt'
  - symbol: C/AEN
    title: 'Cadet Aerospace Education NCO'
    max_grade: 'C/CMSgt'
    min_grade: 'C/SSgt'
  - symbol: C/AEC
    title: 'Cadet Cyber Education Officer'
    max_grade: 'C/Col'
    min_grade: 'C/2d Lt'
  - symbol: C/AECN
    title: 'Cadet Cyber Education NCO'
    max_grade: 'C/CMSgt'
    min_grade: 'C/SSgt'
  - symbol: C/ES
    title: 'Cadet Emergency Services Officer'
    max_grade: 'C/Col'
    min_grade: 'C/2d Lt'
  - symbol: C/ESN
    title: 'Cadet Emergency Services NCO'
    max_grade: 'C/CMSgt'
    min_grade: 'C/SSgt'
  - symbol: C/ESA
    title: 'Cadet Alerting Officer'
    max_grade: 'C/Col'
    min_grade: 'C/2d Lt'
  - symbol: C/ESN
    title: 'Alerting NCO'
    max_grade: 'C/CMSgt'
    min_grade: 'C/SSgt'
  - symbol: C/EST
    title: 'Emergency Services Training Officer'
    max_grade: 'C/Col'
    min_grade: 'C/2d Lt'
  - symbol: C/ESTN
    title: 'Emergency Services Training Officer'
    max_grade: 'C/SrA'
    min_grade: 'C/Amn'
  - symbol: C/LD
    title: 'Leadership Officer'
    max_grade: 'C/Col'
    min_grade: 'C/2d Lt'
  - symbol: C/LDN
    title: 'Leadership Officer'
    max_grade: 'C/CMSgt'
    min_grade: 'C/SSgt'
  - symbol: C/LDA
    title: 'Activities Officer'
    max_grade: 'C/Col'
    min_grade: 'C/2d Lt'
  - symbol: C/LDAN
    title: 'Activities Officer'
    max_grade: 'C/CMSgt'
    min_grade: 'C/SSgt'
  - symbol: C/DA
    title: 'Cadet Administrative Officer'
    max_grade: 'C/Col'
    min_grade: 'C/2d Lt'
  - symbol: C/DAN
    title: 'Cadet Administrative NCO'
    max_grade: 'C/CMSgt'
    min_grade: 'C/SSgt'
  - symbol: C/DAA
    title: 'Cadet Administrative Assistant'
    max_grade: 'C/SrA'
    min_grade: 'C/Amn'
  - symbol: C/DC
    title: 'Cadet Communications Officer'
    max_grade: 'C/Col'
    min_grade: 'C/2d Lt'
  - symbol: C/DCN
    title: 'Cadet Communications NCO'
    max_grade: 'C/CMSgt'
    min_grade: 'C/SSgt'
  - symbol: C/DCA
    title: 'Cadet Communications Assistant'
    max_grade: 'C/SrA'
    min_grade: 'C/Amn'
  - symbol: C/DP
    title: 'Cadet Personnel Officer'
    max_grade: 'C/Col'
    min_grade: 'C/2d Lt'
  - symbol: C/DPN
    title: 'Cadet Personnel NCO'
    max_grade: 'C/CMSgt'
    min_grade: 'C/SSgt'
  - symbol: C/DPA
    title: 'Cadet Personnel Assistant'
    max_grade: 'C/SrA'
    min_grade: 'C/Amn'
  - symbol: C/IT
    title: 'Cadet Information Technology Officer'
    max_grade: 'C/Col'
    min_grade: 'C/2d Lt'
  - symbol: C/ITN
    title: 'Cadet Information Technology NCO'
    max_grade: 'C/CMSgt'
    min_grade: 'C/SSgt'
  - symbol: C/ITA
    title: 'Cadet Information Technology Assistant'
    max_grade: 'C/SrA'
    min_grade: 'C/Amn'
  - symbol: C/LGS
    title: 'Cadet Supply Officer'
    max_grade: 'C/Col'
    min_grade: 'C/2d Lt'
  - symbol: C/LGSN
    title: 'Cadet Supply NCO'
    max_grade: 'C/CMSgt'
    min_grade: 'C/SSgt'
  - symbol: C/PA
    title: 'Cadet Public Affairs Officer'
    max_grade: 'C/Col'
    min_grade: 'C/2d Lt'
  - symbol: C/PAN
    title: 'Cadet Public Affairs NCO'
    max_grade: 'C/CMSgt'
    min_grade: 'C/SSgt'
cadet_line_staff:
  - symbol: AFlt/CC
    title: 'Alpha Flight Commander'
    max_grade: 'C/Capt'
    min_grade: 'C/MSgt'
  - symbol: AFlt/CCF
    title: 'Alpha Flight Sergeant'
    max_grade: 'C/CMSgt'
    min_grade: 'C/SSgt'
  - symbol: AFlt/CCF1
    title: 'Element A-1 Leader'
    max_grade: 'C/CMSgt'
    min_grade: 'C/Amn'
  - symbol: AFlt/CCF2
    title: 'Element A-2 Leader'
    max_grade: 'C/CMSgt'
    min_grade: 'C/Amn'
  - symbol: AFlt/CCF3
    title: 'Element A-3 Leader'
    max_grade: 'C/CMSgt'
    min_grade: 'C/Amn'
  - symbol: AFlt/CCF4
    title: 'Element A-4 Leader'
    max_grade: 'C/CMSgt'
    min_grade: 'C/Amn'
  - symbol: BFlt/CC
    title: 'Bravo Flight Commander'
    max_grade: 'C/Capt'
    min_grade: 'C/MSgt'
  - symbol: BFlt/CCF
    title: 'Bravo Flight Sergeant'
    max_grade: 'C/CMSgt'
    min_grade: 'C/SSgt'
  - symbol: BFlt/CCF1
    title: 'Element B-1 Leader'
    max_grade: 'C/CMSgt'
    min_grade: 'C/Amn'
  - symbol: BFlt/CCF2
    title: 'Element B-2 Leader'
    max_grade: 'C/CMSgt'
    min_grade: 'C/Amn'
  - symbol: BFlt/CCF3
    title: 'Element B-3 Leader'
    max_grade: 'C/CMSgt'
    min_grade: 'C/Amn'
  - symbol: BFlt/CCF4
    title: 'Element B-4 Leader'
    max_grade: 'C/CMSgt'
    min_grade: 'C/Amn'
  - symbol: TC1/CC
    title: 'Cohort 1 Commander'
    max_grade: 'C/Capt'
    min_grade: 'C/MSgt'
  - symbol: TC1/CCF
    title: 'Cohort 1 Flight Sergeant'
    max_grade: 'C/CMSgt'
    min_grade: 'C/SSgt'
  - symbol: TC1/CCF1
    title: 'Element TC1-1 Leader'
    max_grade: 'C/CMSgt'
    min_grade: 'C/Amn'
  - symbol: TC1/CCF2
    title: 'Element TC1-2 Leader'
    max_grade: 'C/CMSgt'
    min_grade: 'C/Amn'
